msgid ""
msgstr ""
"Project-Id-Version: red-discordbot\n"
"POT-Creation-Date: 2020-10-15 12:29+0000\n"
"Last-Translator: \n"
"Language-Team: Turkish\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: redgettext 3.1\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"X-Crowdin-Project: red-discordbot\n"
"X-Crowdin-Project-ID: 289505\n"
"X-Crowdin-Language: tr\n"
"X-Crowdin-File-ID: 670\n"
"Language: tr_TR\n"

#: redbot/cogs/audio/core/events/dpy.py:39
msgid "You have attempted to run Audio's Lavalink server on an unsupported architecture. Only settings related commands will be available."
msgstr "Audio's Lavalink sunucusunu desteklenmeyen bir mimaride çalıştırmayı denediniz. Yalnızca ayarlarla ilgili komutlar kullanılabilir."

#: redbot/cogs/audio/core/events/dpy.py:69
msgid "I'm missing permissions in this server, Please address this as soon as possible.\\n\\nExpected Permissions:\\n"
msgstr ""

#: redbot/cogs/audio/core/events/dpy.py:76
msgid "Enabled"
msgstr "Etkinleştirildi"

#: redbot/cogs/audio/core/events/dpy.py:76
msgid "Disabled"
msgstr "Devre dışı bırakıldı"

#: redbot/cogs/audio/core/events/dpy.py:123
msgid "No DJ role found. Disabling DJ mode."
msgstr "DJ rolü bulunamadı. DJ modu kapatılıyor."

#: redbot/cogs/audio/core/events/dpy.py:133
msgid "`{user_input}` is not a valid value for `{command}`"
msgstr ""

#: redbot/cogs/audio/core/events/dpy.py:141
msgid "Unable To Parse Argument"
msgstr ""

#: redbot/cogs/audio/core/events/dpy.py:153
#: redbot/cogs/audio/core/events/dpy.py:162
msgid "Invalid Argument"
msgstr "Geçersiz argüment"

#: redbot/cogs/audio/core/events/dpy.py:154
msgid "The argument you gave for `{}` is not valid: I was expecting a `{}`."
msgstr ""

#: redbot/cogs/audio/core/events/dpy.py:174
msgid "Invalid Environment"
msgstr "Geçersiz Ortam"

#: redbot/cogs/audio/core/events/dpy.py:175
msgid "Connection to Lavalink has been lost."
msgstr "Lavalink'e bağlanırken bir bağlantı hatası oluştu."

#: redbot/cogs/audio/core/events/dpy.py:183
msgid "No Player Available"
msgstr ""

#: redbot/cogs/audio/core/events/dpy.py:184
msgid "The bot is not connected to a voice channel."
msgstr ""

#: redbot/cogs/audio/core/events/dpy.py:192
#: redbot/cogs/audio/core/events/lavalink.py:94
msgid "Unable to Get Track"
msgstr "Parça alınamıyor"

#: redbot/cogs/audio/core/events/dpy.py:193
#: redbot/cogs/audio/core/events/lavalink.py:95
msgid "I'm unable to get a track from Lavalink at the moment, try again in a few minutes."
msgstr ""

#: redbot/cogs/audio/core/events/dpy.py:204
msgid "There was an issue communicating with Discord."
msgstr ""

#: redbot/cogs/audio/core/events/dpy.py:205
msgid "This error has been reported to the bot owner."
msgstr ""

#: redbot/cogs/audio/core/events/lavalink.py:85
msgid "Couldn't get a valid track."
msgstr "Geçerli bir parça alınamadı."

#: redbot/cogs/audio/core/events/lavalink.py:117
msgid "Auto Play started."
msgstr "Otomatik çalma başladı."

#: redbot/cogs/audio/core/events/lavalink.py:132
msgid "Now Playing"
msgstr "Şimdi oynatılıyor"

#: redbot/cogs/audio/core/events/lavalink.py:134
msgid "Track length: {length} | Requested by: {user}"
msgstr "Şarkı uzunluğu: {length} | Şarkıyı sıraya koyan: {user}"

#: redbot/cogs/audio/core/events/lavalink.py:155
msgid "Queue ended."
msgstr ""

#: redbot/cogs/audio/core/events/lavalink.py:197
msgid "Multiple Errors Detected"
msgstr ""

#: redbot/cogs/audio/core/events/lavalink.py:198
msgid "Closing the audio player due to multiple errors being detected. If this persists, please inform the bot owner as the Audio cog may be temporally unavailable."
msgstr "Birden çok hata nedeniyle müzik çalar kapatılıyor. Hata devam ederse, lütfen bot sahibini bilgilendiriniz. Audio eklentisi geçici olarak devre dışı kalmış olabilir."

#: redbot/cogs/audio/core/events/lavalink.py:212
msgid "Track Stuck"
msgstr "Parça Takıldı"

#: redbot/cogs/audio/core/events/lavalink.py:213
msgid "Playback of the song has stopped due to an unexcepted error.\\n{error}"
msgstr ""

#: redbot/cogs/audio/core/events/lavalink.py:219
msgid "Track Error"
msgstr "Şarkı hatası"

